name: 'Init environment'
description: 'Install dependencies'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Java 13
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: "13"
    - name: Install Dependencies
      run: gradle resolveDependencies
      shell: bash
