name: 'Init environment'
description: 'Install dependencies'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Java 20
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: "20"
    - name: Install Dependencies
      run: gradle resolveDependencies
      shell: bash
