name: 'Init environment'
description: 'Install dependencies'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Java 19
      uses: actions/setup-java@v2
      with:
        java-version: "19"
    - name: Install Dependencies
      run: gradle resolveDependencies
      shell: bash
